export LANG="en_US.UTF-8"

#
# Path to your oh-my-zsh installation.
export ZSH=~/.zsh

# Set name of the theme to load.
# Look in ~/.zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git jump)

# User configuration
source $ZSH/oh-my-zsh.sh
source ~/.zsh/path.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/window.zsh
source ~/.zsh/config.zsh
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.zsh/fzf.zsh

# `Frozing' tty, so after any command terminal settings will be restored
ttyctl -f
